archives:
- format:
  files:
  - none*
  format_overrides:
  - goos: windows
    format: zip
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
snapshot:
  name_template: '{{ .Tag }}'
builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
