name: release

on:
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Required. See https://goreleaser.com/ci/actions
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Should match the Go version described in go.mod
          go-version: '1.21.5'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
